language: ruby
rvm: 1.9.3
env:
  global:
    secure: qw47wfZJRHLrKY0WXVn6OjUPUFJH1Dz4GyqeatpAhI8X/LNqGDBvv5fj1V18TkDzfiK3R8gpIspzk9Eqed54WRu0eAmYcOzY0JdsCgisivM3AzzVS8BIoYWnPTokIzQMvZZRraVVJvOtqPdwUlVBa2EhV72QXhIx3gon/1S1ywI=
install:
    - bundle install
    - rake emoji

before_script:
    - rake tags
    - git config --global user.email "juandebravo@gmail.com"
    - git config --global user.name "Juan de Bravo"

script:
    - git checkout develop
    - jekyll --no-server --no-safe
    - rm -rf tag
    - git checkout master
    - rm -rf 2012 2013 2014 gfx css tag js
    - cp -r _site/* .
    - git add 2012 2013 2014 tag
    - git commit -am "Added new post"

after_success:
    - git config credential.helper "store --file=.git/credentials"
    - git remote set-url origin https://github.com/juandebravo/juandebravo.github.com.git
    - echo "https://${GH_TOKEN}:@github.com" > .git/credentials
    - git push origin master
