language: python
rvm: 2.6
env:
  global:
    secure: qw47wfZJRHLrKY0WXVn6OjUPUFJH1Dz4GyqeatpAhI8X/LNqGDBvv5fj1V18TkDzfiK3R8gpIspzk9Eqed54WRu0eAmYcOzY0JdsCgisivM3AzzVS8BIoYWnPTokIzQMvZZRraVVJvOtqPdwUlVBa2EhV72QXhIx3gon/1S1ywI=

branches:
  only:
    - master

install:
    - bundle install
    - pip install pygments
    - rake emoji

before_script:
    - rm -rf 2012 2013 2014
    - rm -f tag/*
    - rake tags
    - git config --global user.email "juandebravo@gmail.com"
    - git config --global user.name "Juan de Bravo"

script:
    - cp index.html.template index.html
    - cp atom.xml.template atom.xml
    - jekyll --no-safe
    - cp index.html.template index.html.template.back
    - cp atom.xml.template atom.xml.back
    - cp -r _site/* .
    - mv index.html.template.back index.html.template
    - mv atom.xml.back atom.xml.template
    - git add --all 2012 2013 2014 2015 tag atom.xml index.html
    - git commit -am "Added new post"

after_success:
    - git remote set-url origin https://${GH_TOKEN}@github.com/juandebravo/juandebravo.github.com.git
    - git push origin master
